// Mocks generated by Mockito 5.1.0 from annotations
// in character_project/test/pages/home/service/heroes_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:character_project/api/heroes_api.dart' as _i3;
import 'package:character_project/helpers/network_helper.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [HeroesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeroesApi extends _i1.Mock implements _i3.HeroesApi {
  MockHeroesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> getMusicList(_i5.NetworkHelper? helper) =>
      (super.noSuchMethod(Invocation.method(#getMusicList, [helper]),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
}

/// A class which mocks [NetworkHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkHelper extends _i1.Mock implements _i5.NetworkHelper {
  MockNetworkHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> networkGet({String? path, String? query}) =>
      (super.noSuchMethod(
              Invocation.method(#networkGet, [], {#path: path, #query: query}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
}
